// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeddingConfirmationApp.Infrastructure;

#nullable disable

namespace WeddingConfirmationApp.Infrastructure.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20250926130545_Added_SelectedDrink")]
    partial class Added_SelectedDrink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.DrinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrinkType");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InvitationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.PersonConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confimed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectedDrinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SelectedDrinkId");

                    b.ToTable("PersonConfirmations");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.Person", b =>
                {
                    b.HasOne("WeddingConfirmationApp.Domain.Entities.Invitation", null)
                        .WithMany("Persons")
                        .HasForeignKey("InvitationId");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.PersonConfirmation", b =>
                {
                    b.HasOne("WeddingConfirmationApp.Domain.Entities.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingConfirmationApp.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingConfirmationApp.Domain.Entities.DrinkType", "SelectedDrink")
                        .WithMany()
                        .HasForeignKey("SelectedDrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");

                    b.Navigation("Person");

                    b.Navigation("SelectedDrink");
                });

            modelBuilder.Entity("WeddingConfirmationApp.Domain.Entities.Invitation", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
